package com.merryapps.fileowl.model.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.merryapps.fileowl.model.db.LargeFileEntity;
import com.merryapps.fileowl.model.db.FrequentFileEntity;
import com.merryapps.fileowl.model.db.ScanStatEntity;

import com.merryapps.fileowl.model.db.LargeFileEntityDao;
import com.merryapps.fileowl.model.db.FrequentFileEntityDao;
import com.merryapps.fileowl.model.db.ScanStatEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig largeFileEntityDaoConfig;
    private final DaoConfig frequentFileEntityDaoConfig;
    private final DaoConfig scanStatEntityDaoConfig;

    private final LargeFileEntityDao largeFileEntityDao;
    private final FrequentFileEntityDao frequentFileEntityDao;
    private final ScanStatEntityDao scanStatEntityDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        largeFileEntityDaoConfig = daoConfigMap.get(LargeFileEntityDao.class).clone();
        largeFileEntityDaoConfig.initIdentityScope(type);

        frequentFileEntityDaoConfig = daoConfigMap.get(FrequentFileEntityDao.class).clone();
        frequentFileEntityDaoConfig.initIdentityScope(type);

        scanStatEntityDaoConfig = daoConfigMap.get(ScanStatEntityDao.class).clone();
        scanStatEntityDaoConfig.initIdentityScope(type);

        largeFileEntityDao = new LargeFileEntityDao(largeFileEntityDaoConfig, this);
        frequentFileEntityDao = new FrequentFileEntityDao(frequentFileEntityDaoConfig, this);
        scanStatEntityDao = new ScanStatEntityDao(scanStatEntityDaoConfig, this);

        registerDao(LargeFileEntity.class, largeFileEntityDao);
        registerDao(FrequentFileEntity.class, frequentFileEntityDao);
        registerDao(ScanStatEntity.class, scanStatEntityDao);
    }
    
    public void clear() {
        largeFileEntityDaoConfig.getIdentityScope().clear();
        frequentFileEntityDaoConfig.getIdentityScope().clear();
        scanStatEntityDaoConfig.getIdentityScope().clear();
    }

    public LargeFileEntityDao getLargeFileEntityDao() {
        return largeFileEntityDao;
    }

    public FrequentFileEntityDao getFrequentFileEntityDao() {
        return frequentFileEntityDao;
    }

    public ScanStatEntityDao getScanStatEntityDao() {
        return scanStatEntityDao;
    }

}
