package com.merryapps.fileowl.model.db;

import com.merryapps.framework.EntityState;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "FREQUENT_FILE".
 */
public class FrequentFileEntity implements com.merryapps.framework.Entity {

    private Long id;
    /** Not-null value. */
    private String fileType;
    private long fileFrequency;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public FrequentFileEntity() {
    }

    public FrequentFileEntity(Long id) {
        this.id = id;
    }

    public FrequentFileEntity(Long id, String fileType, long fileFrequency, EntityState entityState) {
        this.id = id;
        this.fileType = fileType;
        this.fileFrequency = fileFrequency;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFileType() {
        return fileType;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFileType(String fileType) {
        this.fileType = fileType;
    }

    public long getFileFrequency() {
        return fileFrequency;
    }

    public void setFileFrequency(long fileFrequency) {
        this.fileFrequency = fileFrequency;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here

    public FrequentFileEntity(String fileType, long fileFrequency) {
        this.fileType = fileType;
        this.fileFrequency = fileFrequency;
        entityState = EntityState.LOCAL;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        FrequentFileEntity that = (FrequentFileEntity) o;

        if (fileFrequency != that.fileFrequency) return false;
        return fileType != null ? fileType.equals(that.fileType) : that.fileType == null;

    }

    @Override
    public int hashCode() {
        int result = fileType != null ? fileType.hashCode() : 0;
        result = 31 * result + (int) (fileFrequency ^ (fileFrequency >>> 32));
        return result;
    }

    @Override
    public String toString() {
        return "FrequentFileEntity{" +
                "fileType='" + fileType + '\'' +
                ", fileFrequency=" + fileFrequency +
                '}';
    }
    // KEEP METHODS END

}
