package com.merryapps.fileowl.model.db;

import com.merryapps.framework.EntityState;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "LARGE_FILE".
 */
public class LargeFileEntity implements com.merryapps.framework.Entity {

    private Long id;
    /** Not-null value. */
    private String filePath;
    private long fileSize;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LargeFileEntity() {
    }

    public LargeFileEntity(Long id) {
        this.id = id;
    }

    public LargeFileEntity(Long id, String filePath, long fileSize, EntityState entityState) {
        this.id = id;
        this.filePath = filePath;
        this.fileSize = fileSize;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getFilePath() {
        return filePath;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    public long getFileSize() {
        return fileSize;
    }

    public void setFileSize(long fileSize) {
        this.fileSize = fileSize;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here

    public LargeFileEntity(String filePath, long fileSize) {
        this.filePath = filePath;
        this.fileSize = fileSize;
        entityState = EntityState.LOCAL;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        LargeFileEntity that = (LargeFileEntity) o;

        return filePath != null ? filePath.equals(that.filePath) : that.filePath == null;

    }

    @Override
    public String toString() {
        return "LargeFileEntity{" +
                "filePath='" + filePath + '\'' +
                '}';
    }

    @Override
    public int hashCode() {
        return filePath != null ? filePath.hashCode() : 0;
    }
    // KEEP METHODS END

}
