package com.merryapps.fileowl.model.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.merryapps.framework.EntityState;
import com.merryapps.framework.EntityStateConverter;

import com.merryapps.fileowl.model.db.ScanStatEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SCAN_STAT".
*/
public class ScanStatEntityDao extends AbstractDao<ScanStatEntity, Long> {

    public static final String TABLENAME = "SCAN_STAT";

    /**
     * Properties of entity ScanStatEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property TotalFilesScanned = new Property(1, long.class, "totalFilesScanned", false, "TOTAL_FILES_SCANNED");
        public final static Property AverageFileSize = new Property(2, long.class, "averageFileSize", false, "AVERAGE_FILE_SIZE");
        public final static Property ScanTime = new Property(3, long.class, "scanTime", false, "SCAN_TIME");
        public final static Property EntityState = new Property(4, String.class, "entityState", false, "ENTITY_STATE");
    };

    private final EntityStateConverter entityStateConverter = new EntityStateConverter();

    public ScanStatEntityDao(DaoConfig config) {
        super(config);
    }
    
    public ScanStatEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SCAN_STAT\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"TOTAL_FILES_SCANNED\" INTEGER NOT NULL UNIQUE ," + // 1: totalFilesScanned
                "\"AVERAGE_FILE_SIZE\" INTEGER NOT NULL UNIQUE ," + // 2: averageFileSize
                "\"SCAN_TIME\" INTEGER NOT NULL UNIQUE ," + // 3: scanTime
                "\"ENTITY_STATE\" TEXT NOT NULL );"); // 4: entityState
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SCAN_STAT\"";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, ScanStatEntity entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getTotalFilesScanned());
        stmt.bindLong(3, entity.getAverageFileSize());
        stmt.bindLong(4, entity.getScanTime());
        stmt.bindString(5, entityStateConverter.convertToDatabaseValue(entity.getEntityState()));
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public ScanStatEntity readEntity(Cursor cursor, int offset) {
        ScanStatEntity entity = new ScanStatEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // totalFilesScanned
            cursor.getLong(offset + 2), // averageFileSize
            cursor.getLong(offset + 3), // scanTime
            entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)) // entityState
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, ScanStatEntity entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTotalFilesScanned(cursor.getLong(offset + 1));
        entity.setAverageFileSize(cursor.getLong(offset + 2));
        entity.setScanTime(cursor.getLong(offset + 3));
        entity.setEntityState(entityStateConverter.convertToEntityProperty(cursor.getString(offset + 4)));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(ScanStatEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(ScanStatEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
