package com.merryapps.fileowl.model.db;

import com.merryapps.fileowl.model.ScanStatus;
import com.merryapps.framework.EntityState;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SCAN_STAT".
 */
public class ScanStatEntity implements com.merryapps.framework.Entity {

    private Long id;
    private long totalFilesScanned;
    private long averageFileSize;
    private long scanTime;
    /** Not-null value. */
    private ScanStatus scanStatus;
    /** Not-null value. */
    private EntityState entityState;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public ScanStatEntity() {
    }

    public ScanStatEntity(Long id) {
        this.id = id;
    }

    public ScanStatEntity(Long id, long totalFilesScanned, long averageFileSize, long scanTime, ScanStatus scanStatus, EntityState entityState) {
        this.id = id;
        this.totalFilesScanned = totalFilesScanned;
        this.averageFileSize = averageFileSize;
        this.scanTime = scanTime;
        this.scanStatus = scanStatus;
        this.entityState = entityState;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getTotalFilesScanned() {
        return totalFilesScanned;
    }

    public void setTotalFilesScanned(long totalFilesScanned) {
        this.totalFilesScanned = totalFilesScanned;
    }

    public long getAverageFileSize() {
        return averageFileSize;
    }

    public void setAverageFileSize(long averageFileSize) {
        this.averageFileSize = averageFileSize;
    }

    public long getScanTime() {
        return scanTime;
    }

    public void setScanTime(long scanTime) {
        this.scanTime = scanTime;
    }

    /** Not-null value. */
    public ScanStatus getScanStatus() {
        return scanStatus;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setScanStatus(ScanStatus scanStatus) {
        this.scanStatus = scanStatus;
    }

    /** Not-null value. */
    public EntityState getEntityState() {
        return entityState;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEntityState(EntityState entityState) {
        this.entityState = entityState;
    }

    // KEEP METHODS - put your custom methods here


    public ScanStatEntity(Long id, long totalFilesScanned, long averageFileSize, long scanTime, ScanStatus status) {
        this.id = id;
        this.totalFilesScanned = totalFilesScanned;
        this.averageFileSize = averageFileSize;
        this.scanTime = scanTime;
        this.scanStatus = status;
        this.entityState = EntityState.LOCAL;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        ScanStatEntity that = (ScanStatEntity) o;

        if (totalFilesScanned != that.totalFilesScanned) return false;
        if (averageFileSize != that.averageFileSize) return false;
        if (scanTime != that.scanTime) return false;
        return scanStatus == that.scanStatus;

    }

    @Override
    public int hashCode() {
        int result = (int) (totalFilesScanned ^ (totalFilesScanned >>> 32));
        result = 31 * result + (int) (averageFileSize ^ (averageFileSize >>> 32));
        result = 31 * result + (int) (scanTime ^ (scanTime >>> 32));
        result = 31 * result + (scanStatus != null ? scanStatus.hashCode() : 0);
        return result;
    }

    @Override
    public String toString() {
        return "ScanStatEntity{" +
                "id=" + id +
                ", totalFilesScanned=" + totalFilesScanned +
                ", averageFileSize=" + averageFileSize +
                ", scanTime=" + scanTime +
                ", scanStatus=" + scanStatus +
                ", entityState=" + entityState +
                '}';
    }
    // KEEP METHODS END

}
